// generated by cdktf get
// git::https://github.com/prefapp/tfm.git//modules/aws-oidc?ref=main
import { TerraformModule, TerraformModuleUserConfig } from 'cdktf';
import { Construct } from 'constructs';
export interface AwsOidcConfig extends TerraformModuleUserConfig {
  /**
  */
  readonly organization: string;
  /**
  * eu-west-1
  */
  readonly region?: string;
  /**
  */
  readonly subs: string[];
}
/**
* Defines an AwsOidc based on a Terraform module
*
* Source at git::https://github.com/prefapp/tfm.git//modules/aws-oidc?ref=main
*/
export class AwsOidc extends TerraformModule {
  private readonly inputs: { [name: string]: any } = { }
  public constructor(scope: Construct, id: string, config: AwsOidcConfig) {
    super(scope, id, {
      ...config,
      source: 'git::https://github.com/prefapp/tfm.git//modules/aws-oidc?ref=main',
    });
    this.organization = config.organization;
    this.region = config.region;
    this.subs = config.subs;
  }
  public get organization(): string {
    return this.inputs['organization'] as string;
  }
  public set organization(value: string) {
    this.inputs['organization'] = value;
  }
  public get region(): string | undefined {
    return this.inputs['region'] as string | undefined;
  }
  public set region(value: string | undefined) {
    this.inputs['region'] = value;
  }
  public get subs(): string[] {
    return this.inputs['subs'] as string[];
  }
  public set subs(value: string[]) {
    this.inputs['subs'] = value;
  }
  public get oidcRoleArnOutput() {
    return this.getString('oidc_role_arn')
  }
  protected synthesizeAttributes() {
    return this.inputs;
  }
}
