// generated by cdktf get
// terraform-aws-modules/iam/aws//examples/iam-policy
import { TerraformModule, TerraformModuleUserConfig } from 'cdktf';
import { Construct } from 'constructs';
export interface IamPolicyConfig extends TerraformModuleUserConfig {
}
/**
* Defines an IamPolicy based on a Terraform module
*
* Docs at Terraform Registry: {@link https://registry.terraform.io/modules/terraform-aws-modules/iam/aws//examples/iam-policy terraform-aws-modules/iam/aws//examples/iam-policy}
*/
export class IamPolicy extends TerraformModule {
  private readonly inputs: { [name: string]: any } = { }
  public constructor(scope: Construct, id: string, config: IamPolicyConfig = {}) {
    super(scope, id, {
      ...config,
      source: 'terraform-aws-modules/iam/aws//examples/iam-policy',
      version: '5.32.0',
    });
  }
  public get arnOutput() {
    return this.getString('arn')
  }
  public get descriptionOutput() {
    return this.getString('description')
  }
  public get idOutput() {
    return this.getString('id')
  }
  public get nameOutput() {
    return this.getString('name')
  }
  public get pathOutput() {
    return this.getString('path')
  }
  public get policyOutput() {
    return this.getString('policy')
  }
  protected synthesizeAttributes() {
    return this.inputs;
  }
}
